namaLengkap = input("Masukkan nama lengkap Anda:")
namaPanggilan = input("Masukkan nama panggilan Anda:")
alamat =input("Masukkan alamat Anda:")
jenisKelamin = input("Masukkan jenis kelamin Anda:")
golonganDarah = input("Masukkan golongan darah Anda:")
riwayatPenyakit = input("Masukkan riwayat penyakit Anda:")
pantanganMakanan = input("Masukkan pantangan makanan Anda:")
umur = input("Masukkan umur Anda:")
tinggiBadan = input("Masukkan tinggi badan Anda:")
beratBadan = input("Masukkan berat badan Anda:")

print("Nama lengkap Anda adalah " + namaLengkap)
print("Nama panggilan Anda adalah " + namaPanggilan)
print("Anda beralamat di " + alamat)
print("Jenis kelamin Anda adalah " + jenisKelamin)
print("Golongan darah Anda adalah " + golonganDarah)
print("Riwayat penyakit Anda adalah " + riwayatPenyakit)
print("Pantangan makanan Anda adalah " + pantanganMakanan)
print("Umur Anda adalah " + umur)
print("Tinggi badan Anda adalah " + tinggiBadan)
print("Berat badan Anda adalah " + beratBadan)